1. Import the numpy package under the name

In [29]:
import numpy as np

2. Print the numpy version and the configuration

In [30]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

3. Create a null vector of size 10

In [31]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [32]:
y = np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
s = np.arange(9).reshape(3, 3)
print(s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
n = np.random.random((10,10))
nmin, nmax = n.min(), n.max()
print(n, nmin, nmax, sep='\n')

[[0.48019677 0.5036466  0.02233382 0.50356246 0.22261158 0.5533413
  0.5682451  0.79783703 0.24840478 0.84427986]
 [0.21143608 0.48087823 0.52622914 0.77937241 0.32078236 0.51962279
  0.02333201 0.96294109 0.37936712 0.85138242]
 [0.3089796  0.24795777 0.67037795 0.29707814 0.64197089 0.16339553
  0.27303163 0.19295269 0.57523688 0.12676547]
 [0.3604096  0.32784319 0.27289831 0.55419718 0.35594357 0.24616897
  0.00271158 0.43117363 0.37205383 0.2908571 ]
 [0.32283076 0.19823985 0.49094374 0.38073346 0.54831219 0.7000918
  0.18951156 0.09368712 0.80189538 0.87509916]
 [0.83377215 0.16104818 0.06343597 0.61155804 0.81805128 0.57091217
  0.39914719 0.88920722 0.43744921 0.20633572]
 [0.43228218 0.14941758 0.38420761 0.929788   0.91653743 0.32263051
  0.14396934 0.18626951 0.2654497  0.27428901]
 [0.46968001 0.97517164 0.96264129 0.46821473 0.28722618 0.16036877
  0.30860465 0.93851812 0.08225697 0.80359869]
 [0.97066472 0.05972094 0.09602165 0.80836595 0.82283427 0.29424863
  0.49282584 0

22. Normalize a 5x5 random matrix

In [35]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.16585592  1.36383007  0.73147659  1.22048493  0.92840771]
 [-0.15800794 -0.90494566 -0.87613759  1.84371856 -0.46933362]
 [-0.2333577   0.81289774  1.59899495 -0.62616775 -1.74131389]
 [-1.39594627  0.40580328 -1.19508938 -1.42309473  0.36978277]
 [ 0.78918858 -1.08841436  0.57689133 -0.62265789  0.2588462 ]]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [36]:
K = np.dot(np.ones((5,3)), np.ones((3,2)))
print(K)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


30. How to find common values between two arrays?

In [37]:
c1 = np.random.randint(0,10,10)
c2 = np.random.randint(0,10,10)
print(c1, c2, np.intersect1d(c1,c2), sep='\n')

[4 8 6 3 2 2 0 4 3 4]
[6 5 6 5 8 6 3 9 9 8]
[3 6 8]
